name: plus_one
description: "Plus One Application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/modules/auth/
    - lib/modules/auth/data/
    - lib/modules/auth/data/models/
    - lib/modules/auth/data/datasources/
    - lib/modules/auth/data/repositories/

